import Main from '../components/UI/Main';
import Navbar from '../components/navbar/Navbar';

import { useEffect } from 'react';

const Paslaugos = () => {
    useEffect(() => {
        // document.body.style.backgroundColor = '#eff1ef';
        document.title = 'Be žalos | Paslaugos';
    }, []);
    return (
        <>
            <Navbar />
            <Main>
                <h1>Paslaugos</h1>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
                <div>Paslaugos</div>
            </Main>
        </>
        
    );
};

export default Paslaugos;