import Main from '../components/UI/Main';
import Navbar from '../components/navbar/Navbar';

import { useEffect } from 'react';

const Virtuve = () => {
    
    useEffect(() => {
        document.body.style.backgroundColor = '#eff1ef';
        document.title = 'Be žalos | Virtuvė';
    }, []);
    
    return (
        <>
            <Navbar />
            <Main>
                <h1>Virtuvė</h1>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
                <div>virtuve</div>
            </Main>
        </>
    );
};

export default Virtuve;