import { HeroSection } from '../../../features/client/homepage/components';

const HomePage = () => {
    return (
        <>
            <HeroSection />
            <div>Pirmas</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>

            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
            <div>yra</div>
        </>
    );
};

export default HomePage;