name: Deploy Be žalos

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, '[dev]') || contains(github.event.head_commit.message, '[prod]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

    #   - name: Cache node modules
    #     uses: actions/cache@v3
    #     id: cache-nodemodules
    #     with:
    #       path: node_modules
    #       key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    #       restore-keys: |
    #         ${{ runner.os }}-node-

      - name: Install dependencies
        # if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

    #   - name: Cache build
    #     uses: actions/cache@v3
    #     id: cache-build
    #     with:
    #       path: dist
    #       key: build-${{ github.sha }}

      - name: Build bezalos
        # if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 1

  # DEV deployment
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.head_commit.message, '[dev]')

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Deploy to HOSTINGER
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: 'dist/*'
          target: ${{ secrets.DEV_DEPLOY_PATH }}

  # PROD deployment
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.head_commit.message, '[prod]')

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Deploy to AWS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: 'dist/*'
          target: ${{ secrets.PROD_DEPLOY_PATH }}
